### ISSUE TITLE
Basic repo setup

### ISSUE THREAD

**Issue by prestwich** [alloy-rs/examples#1]
This repo homes example code that is too large to fit in a doctest

- [x] README.md w/ description and links to examples
- [x] Workspace Cargo.toml w/ git dependency
- [x] CI to run against

Future
- [x] dep on published versions of alloy
- [x] pre-release process for alloy including updating examples

**Comment by zerosnacks** [comment]
Added a dedicated ticket for the [CI workflow](https://github.com/alloy-rs/examples/issues/19) to align on requirements

**Comment by zerosnacks** [comment]
PR for the CI: https://github.com/alloy-rs/examples/pull/22
